development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  database: rendezvous_test
  username: travis
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 173.194.85.37
  database: rendezvous_production
  username: rendezvous
  password: rendezvous
