defaults: &defaults
  rendezvous:
    app_host: https://rendezvous.aiming-inc.biz/

  permited_login_domain: aiming-inc.com

  google_api:
    client_id: 747447196694-t99hgok3h0r1dp0f9qts3lehpmpfpqsu.apps.googleusercontent.com
    secret: bpBWI1xG_GHOwYE8RLZAjoSA

  s3:
    access_key_id: <%= ENV['RV_S3_ASSESS_KEY_ID'] %>
    secret_access_key: <%= ENV['RV_S3_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['RV_S3_BACKET_NAME'] %>

  # optional
  hipchat:
    token: <%= ENV['RV_HIPCHAT_TOKEN'] %>
    room: <%= ENV['RV_HIPCHAT_ROOM'] %>

  # optional
  google_analytics: <%= ENV['RV_GOOGLE_ANALYTICS_ID'] %>

  # optional
  enable_pdf_uploading: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

